### ISSUE TITLE
Bug update line with task

### ISSUE THREAD

**Issue by SuperKali** [MisteFr/ScoreboardsPE#6] opened 2018-10-18 19:11 UTC
![94040f12-ac9a-4e5f-89d0-92014b4279d4](https://user-images.githubusercontent.com/19473898/47178022-47ae0f00-d31a-11e8-9d1f-e86265af9e70.png)

**Comment by MisteFr** [comment] 2018-10-19 05:05
Can you describe more your issue and are you using PocketMine ? Thanks

**Comment by SuperKali** [comment] 2018-10-19 10:20
When I use this api, with setLine, the text isn't update.

**Comment by SuperKali** [comment] 2018-10-19 10:21
With pmmp also the text isn't update

**Comment by SuperKali** [comment] 2018-10-19 10:21
With pocketmine the text isn't update

**Comment by MisteFr** [comment] 2018-10-19 13:48
1) As I saw in your previous issue, it looks like you aren't using PMMP.
2) Can you send me the code you are using to set the line (if you are on PMMP) ? For me all is perfectly working.

**Comment by SuperKali** [comment] 2018-10-19 14:09
`        $score = new Scoreboard($this->getListener()->getMain()->getServer()->getPluginManager()->getPlugin("ScoreboardsPE")->getPlugin(), C::BOLD . C::RED . "Network" . C::AQUA . "Games " . C::RESET . C::GRAY . API::getServer("play.networkgames.eu", 19132)->getOnlinePlayers() . "/400", ScoreboardAction::CREATE);
        $score->create(ScoreboardDisplaySlot::SIDEBAR, ScoreboardSort::DESCENDING);
        $score->setLine($this->getPlayer(), 2, C::BOLD . C::GREEN . "Account");
        $score->setLine($this->getPlayer(), 3, C::WHITE . $this->getPlayer()->getName());
        $score->setLine($this->getPlayer(), 5, C::BOLD . C::GOLD . "Soldi");
        $score->setLine($this->getPlayer(), 6, C::WHITE . $this->getListener()->getMain()->eco->myMoney($this->getPlayer()));
        $score->setLine($this->getPlayer(), 8, C::BOLD . C::AQUA . "Rank");
        $score->setLine($this->getPlayer(), 9, C::WHITE . $this->getListener()->getMain()->pure->getUserDataMgr()->getGroup($this->getPlayer())->getName());
        $score->setLine($this->getPlayer(), 11, C::BOLD . C::RED . "Elo");
        $score->setLine($this->getPlayer(), 12, C::WHITE . $this->getListener()->getMain()->getElo($this->getPlayer()));
        $score->setLine($this->getPlayer(), 14, C::BOLD . C::YELLOW . "Server");
        $score->setLine($this->getPlayer(), 15, C::WHITE . "play.networkgames.eu ");
        $score->addDisplay($this->getPlayer());`

**Comment by SuperKali** [comment] 2018-10-19 14:13
$score = new Scoreboard($this->getListener()->getMain()->getServer()->getPluginManager()->getPlugin("ScoreboardsPE")->getPlugin(), C::BOLD . C::RED . "Network" . C::AQUA . "Games " . C::RESET . C::GRAY . API::getServer("play.networkgames.eu", 19132)->getOnlinePlayers() . "/400", ScoreboardAction::CREATE);
$score->create(ScoreboardDisplaySlot::SIDEBAR, ScoreboardSort::DESCENDING);
$score->setLine($this->getPlayer(), 2, C::BOLD . C::GREEN . "Account");
$score->setLine($this->getPlayer(), 3, C::WHITE . $this->getPlayer()->getName());
$score->setLine($this->getPlayer(), 5, C::BOLD . C::GOLD . "Soldi");
$score->setLine($this->getPlayer(), 6, C::WHITE . $this->getListener()->getMain()->eco->myMoney($this->getPlayer()));
$score->setLine($this->getPlayer(), 8, C::BOLD . C::AQUA . "Rank");
$score->setLine($this->getPlayer(), 9, C::WHITE . $this->getListener()->getMain()->pure->getUserDataMgr()->getGroup($this->getPlayer())->getName());
$score->setLine($this->getPlayer(), 11, C::BOLD . C::RED . "Elo");
$score->setLine($this->getPlayer(), 12, C::WHITE . $this->getListener()->getMain()->getElo($this->getPlayer()));
$score->setLine($this->getPlayer(), 14, C::BOLD . C::YELLOW . "Server");
$score->setLine($this->getPlayer(), 15, C::WHITE . "play.networkgames.eu ");
$score->addDisplay($this->getPlayer());
@MisteFr

**Comment by MisteFr** [comment] 2018-10-19 15:04
Probably a client issue because all is working for me

**Comment by MisteFr** [comment] 2018-10-23 17:38
Reproduced this bug @SuperKali.
It will be fixed in the next commit.

**Closed as completed** 2018-10-23 17:42 UTC
